
## Configuring with the image  otel/opentelemetry-collector-k8s
mode: "deployment"
namespaceOverride: "otel-demo"

presets:
  kubernetesAttributes:
    enabled: true

config:
  exporters:
    debug: {}
    otlphttp:
      endpoint: http://loki-gateway.otel-demo.svc.cluster.local/otlp/
    otlphttp/prometheus:
      endpoint: http://prometheus-demo-server/api/v1/otlp
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
  service:
    extensions:
    - health_check
    pipelines:
      logs:
        exporters:
        - debug
        - otlphttp
        processors:
        - memory_limiter
        - batch
        - k8sattributes
        receivers:
        - otlp
      metrics:
        exporters:
        - debug
        - otlphttp/prometheus
        processors:
        - memory_limiter
        - batch
        - k8sattributes
        receivers:
        - otlp
      traces:
        exporters:
        - debug
        - otlp
        processors:
        - memory_limiter
        - batch
        - k8sattributes
        receivers:
        - otlp

image:
  repository: "otel/opentelemetry-collector-k8s"

command:
  name: "otelcol-k8s"
  extraArgs: []

ports:
  prometheus:
    enabled: true
    containerPort: 9201
    servicePort: 9201
    hostPort: 9201
    protocol: TCP

resources:
  limits:
    cpu: 250m
    memory: 512Mi
